"""Wire protocol types for the NemoClaw Message Bus.

Every WebSocket frame is a JSON object with a required ``op`` field.
This module defines the enum types, message dataclass, and
parse/serialize helpers that both the broker and client use.

See ``docs/nmb_design.md`` sections 5–6 for the full protocol spec.
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from nemoclaw_escapades.config import DEFAULT_NMB_MAX_PAYLOAD_BYTES

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Op(StrEnum):
    """Wire-level operation codes (``op`` field in every frame).

    Values are lower-case strings that appear directly in the JSON.
    """

    # Client -> Broker
    SEND = "send"
    REQUEST = "request"
    REPLY = "reply"
    SUBSCRIBE = "subscribe"
    UNSUBSCRIBE = "unsubscribe"
    PUBLISH = "publish"
    STREAM = "stream"

    # Broker -> Client
    DELIVER = "deliver"
    ACK = "ack"
    ERROR = "error"
    TIMEOUT = "timeout"


class ErrorCode(StrEnum):
    """Broker error codes returned in ``error`` frames.

    Each value is an upper-case constant that appears in the ``code``
    field of error frames on the wire.
    """

    TARGET_OFFLINE = "TARGET_OFFLINE"
    TARGET_UNKNOWN = "TARGET_UNKNOWN"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    RATE_LIMITED = "RATE_LIMITED"
    CHANNEL_FULL = "CHANNEL_FULL"
    INVALID_FRAME = "INVALID_FRAME"
    POLICY_DENIED = "POLICY_DENIED"


class DeliveryStatus(StrEnum):
    """Audit DB delivery status for a logged message."""

    DELIVERED = "delivered"
    ERROR = "error"
    TIMEOUT = "timeout"


# ---------------------------------------------------------------------------
# Required fields per operation
# ---------------------------------------------------------------------------

# Maps each ``Op`` to the set of **dataclass** field names that must be
# non-``None`` for the frame to be valid.  Used by ``validate_frame``.
_REQUIRED_FIELDS: dict[Op, set[str]] = {
    Op.SEND: {"id", "to_sandbox", "type", "payload"},
    Op.REQUEST: {"id", "to_sandbox", "type", "payload"},
    Op.REPLY: {"id", "reply_to", "type", "payload"},
    Op.SUBSCRIBE: {"channel"},
    Op.UNSUBSCRIBE: {"channel"},
    Op.PUBLISH: {"channel", "type", "payload"},
    Op.STREAM: {"to_sandbox", "stream_id", "seq", "payload"},
    # Broker -> Client (generated by broker, not validated on inbound)
    Op.DELIVER: {"id", "from_sandbox", "type", "payload"},
    Op.ACK: {"id"},
    Op.ERROR: {"id", "code", "message"},
    Op.TIMEOUT: {"id"},
}


# ---------------------------------------------------------------------------
# Message model
# ---------------------------------------------------------------------------


class NMBMessage(BaseModel):
    """A single NMB wire-protocol message.

    Represents both client-to-broker and broker-to-client frames.
    Fields that are irrelevant for a given ``op`` are ``None``.

    Both sandbox-addressing fields use the ``_sandbox`` suffix
    (``from_sandbox`` and ``to_sandbox``) so that the Python names,
    the wire-protocol JSON keys, and the audit DB columns are all
    identical — no translation layer needed.

    Unknown fields in incoming JSON are silently ignored
    (``extra="ignore"``) so that newer clients don't break older
    brokers.

    Attributes:
        op: Wire operation code.
        id: Message UUID (auto-generated if not provided).
        from_sandbox: Sender sandbox ID.  The broker overwrites this
            with the authenticated connection identity — never trust
            client-supplied values.
        to_sandbox: Target sandbox ID for point-to-point operations
            (``send``, ``request``, ``stream``).
        type: Application-level message type (e.g. ``task.assign``).
        reply_to: Original request ID for ``reply`` frames.
        channel: Pub/sub channel name.
        stream_id: Stream identifier for ``stream`` frames.
        seq: Sequence number within a stream.
        done: Whether this is the final chunk of a stream.
        timeout: Request timeout in seconds (for ``request`` frames).
        timestamp: Unix epoch seconds (set by broker on delivery).
        payload: Arbitrary JSON-serialisable payload dict.
        code: Error code string (for ``error`` frames).
        message: Human-readable error or timeout description.
    """

    model_config = ConfigDict(extra="ignore")

    op: Op
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    from_sandbox: str | None = None
    to_sandbox: str | None = None
    type: str | None = None
    reply_to: str | None = None
    channel: str | None = None
    stream_id: str | None = None
    seq: int | None = None
    done: bool | None = None
    timeout: float | None = None
    timestamp: float | None = None
    payload: dict[str, Any] | None = None
    code: str | None = None
    message: str | None = None

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate_frame(self) -> None:
        """Validate this frame against per-``op`` required-field rules.

        Checks that all fields listed in ``_REQUIRED_FIELDS`` for this
        message's ``op`` are non-``None``, and that the payload (if
        present) does not exceed ``MAX_PAYLOAD_BYTES``.

        Raises:
            FrameValidationError: If required fields are missing, the
                ``op`` is unknown, or the payload exceeds the size
                limit.
        """
        required = _REQUIRED_FIELDS.get(self.op)
        if required is None:
            raise FrameValidationError(
                ErrorCode.INVALID_FRAME,
                f"Unknown op: {self.op}",
            )

        for field_name in required:
            if getattr(self, field_name, None) is None:
                raise FrameValidationError(
                    ErrorCode.INVALID_FRAME,
                    f"Missing required field '{field_name}' for op={self.op.value}",
                )

        if self.payload is not None:
            payload_bytes = len(json.dumps(self.payload).encode())
            if payload_bytes > DEFAULT_NMB_MAX_PAYLOAD_BYTES:
                raise FrameValidationError(
                    ErrorCode.PAYLOAD_TOO_LARGE,
                    f"Payload size {payload_bytes} exceeds "
                    f"{DEFAULT_NMB_MAX_PAYLOAD_BYTES} byte limit",
                )

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def to_json(self) -> str:
        """Serialize this message to a JSON string for the wire.

        ``None`` fields are omitted to keep frames compact.  Enum
        fields are serialized as their string values.

        Returns:
            A JSON string ready to send as a WebSocket text frame.
        """
        return self.model_dump_json(exclude_none=True)

    @classmethod
    def from_json(cls, raw: str) -> NMBMessage:
        """Parse a JSON WebSocket text frame into an ``NMBMessage``.

        Delegates to pydantic's ``model_validate_json`` which handles
        JSON parsing, type coercion (e.g. ``"send"`` → ``Op.SEND``),
        and field-type validation in one step.  Unknown fields are
        silently ignored for forward compatibility.

        Args:
            raw: The raw JSON string received from the WebSocket.

        Returns:
            A populated and type-validated ``NMBMessage`` instance.

        Raises:
            FrameValidationError: If the JSON is malformed, the ``op``
                field is missing or unrecognised, or any field has the
                wrong type.
        """
        try:
            return cls.model_validate_json(raw)
        except ValidationError as exc:
            raise FrameValidationError(
                ErrorCode.INVALID_FRAME,
                str(exc),
            ) from exc


@dataclass
class PendingRequest:
    """Broker-side tracker for an in-flight request-reply exchange.

    Attributes:
        request_id: The ``id`` of the original ``request`` frame.
        from_sandbox: The sandbox that sent the request (reply target).
        created_at: Unix epoch seconds when the request was received.
        timeout: Seconds after which the broker sends a ``timeout``
            frame.  Defaults to 300 s; the broker overrides this with
            its configured ``default_request_timeout`` at registration
            time.
    """

    request_id: str
    from_sandbox: str
    created_at: float = field(default_factory=time.time)
    timeout: float = 300.0


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


class FrameValidationError(Exception):
    """Raised when an inbound frame fails validation.

    Attributes:
        code: The ``ErrorCode`` describing the failure category.
    """

    def __init__(self, code: ErrorCode, message: str) -> None:
        """Create a validation error.

        Args:
            code: Structured error code to include in the error frame
                sent back to the client.
            message: Human-readable description of the problem.
        """
        super().__init__(message)
        self.code = code
