"""Wire protocol types for the NemoClaw Message Bus.

Every WebSocket frame is a JSON object with a required ``op`` field.
This module defines the enum types, message dataclass, and
parse/serialize helpers that both the broker and client use.

See ``docs/nmb_design.md`` sections 5–6 for the full protocol spec.
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any

MAX_PAYLOAD_BYTES: int = 10 * 1024 * 1024  # 10 MB


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Op(str, Enum):
    """Wire-level operation codes (``op`` field in every frame)."""

    # Client -> Broker
    SEND = "send"
    REQUEST = "request"
    REPLY = "reply"
    SUBSCRIBE = "subscribe"
    UNSUBSCRIBE = "unsubscribe"
    PUBLISH = "publish"
    STREAM = "stream"

    # Broker -> Client
    DELIVER = "deliver"
    ACK = "ack"
    ERROR = "error"
    TIMEOUT = "timeout"


class ErrorCode(str, Enum):
    """Broker error codes returned in ``error`` frames."""

    TARGET_OFFLINE = "TARGET_OFFLINE"
    TARGET_UNKNOWN = "TARGET_UNKNOWN"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    RATE_LIMITED = "RATE_LIMITED"
    CHANNEL_FULL = "CHANNEL_FULL"
    INVALID_FRAME = "INVALID_FRAME"


class DeliveryStatus(str, Enum):
    """Audit DB delivery status for a logged message."""

    DELIVERED = "delivered"
    ERROR = "error"
    TIMEOUT = "timeout"


# ---------------------------------------------------------------------------
# Required fields per operation
# ---------------------------------------------------------------------------

_REQUIRED_FIELDS: dict[Op, set[str]] = {
    Op.SEND: {"id", "to", "type", "payload"},
    Op.REQUEST: {"id", "to", "type", "payload"},
    Op.REPLY: {"id", "reply_to", "type", "payload"},
    Op.SUBSCRIBE: {"channel"},
    Op.UNSUBSCRIBE: {"channel"},
    Op.PUBLISH: {"channel", "type", "payload"},
    Op.STREAM: {"to", "stream_id", "seq", "payload"},
    # Broker -> Client (generated by broker, not validated on inbound)
    Op.DELIVER: {"id", "from_sandbox", "type", "payload"},
    Op.ACK: {"id"},
    Op.ERROR: {"id", "code", "message"},
    Op.TIMEOUT: {"id"},
}


# ---------------------------------------------------------------------------
# Message dataclass
# ---------------------------------------------------------------------------


@dataclass
class NMBMessage:
    """A single NMB wire-protocol message.

    Represents both client-to-broker and broker-to-client frames.
    Fields that are irrelevant for a given ``op`` are ``None``.

    Attributes:
        op: Wire operation code.
        id: Message UUID (auto-generated if not provided).
        from_sandbox: Sender sandbox ID (overwritten by broker from
            the connection registry — never trust client-supplied values).
        to: Target sandbox ID for point-to-point operations.
        type: Application-level message type (e.g. ``task.assign``).
        reply_to: Original request ID for ``reply`` frames.
        channel: Pub/sub channel name.
        stream_id: Stream identifier for ``stream`` frames.
        seq: Sequence number within a stream.
        done: Whether this is the final chunk of a stream.
        timeout: Request timeout in seconds (for ``request`` frames).
        timestamp: Unix epoch seconds (set by broker on delivery).
        payload: Arbitrary JSON-serialisable payload dict.
        code: Error code (for ``error`` frames).
        message: Human-readable error or timeout description.
    """

    op: Op
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    from_sandbox: str | None = None
    to: str | None = None
    type: str | None = None
    reply_to: str | None = None
    channel: str | None = None
    stream_id: str | None = None
    seq: int | None = None
    done: bool | None = None
    timeout: float | None = None
    timestamp: float | None = None
    payload: dict[str, Any] | None = None
    code: str | None = None
    message: str | None = None


@dataclass
class PendingRequest:
    """Broker-side tracker for an in-flight request-reply exchange.

    Attributes:
        request_id: The ``id`` of the original ``request`` frame.
        from_sandbox: The sandbox that sent the request (reply target).
        created_at: Unix epoch seconds when the request was received.
        timeout: Seconds after which the broker sends a ``timeout`` frame.
    """

    request_id: str
    from_sandbox: str
    created_at: float = field(default_factory=time.time)
    timeout: float = 300.0


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


class FrameValidationError(Exception):
    """Raised when an inbound frame fails validation."""

    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code


def validate_frame(msg: NMBMessage) -> None:
    """Validate an inbound frame against required-field rules.

    Args:
        msg: The parsed message to validate.

    Raises:
        FrameValidationError: If required fields are missing or the
            payload exceeds the size limit.
    """
    required = _REQUIRED_FIELDS.get(msg.op)
    if required is None:
        raise FrameValidationError(
            ErrorCode.INVALID_FRAME,
            f"Unknown op: {msg.op}",
        )

    for field_name in required:
        value = getattr(msg, field_name, None)
        if value is None:
            raise FrameValidationError(
                ErrorCode.INVALID_FRAME,
                f"Missing required field '{field_name}' for op={msg.op.value}",
            )

    if msg.payload is not None:
        payload_bytes = len(json.dumps(msg.payload).encode())
        if payload_bytes > MAX_PAYLOAD_BYTES:
            raise FrameValidationError(
                ErrorCode.PAYLOAD_TOO_LARGE,
                f"Payload size {payload_bytes} exceeds {MAX_PAYLOAD_BYTES} byte limit",
            )


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------


def serialize_frame(msg: NMBMessage) -> str:
    """Serialize an ``NMBMessage`` to a JSON string for the wire.

    ``None`` fields are omitted from the output to keep frames compact.

    Args:
        msg: The message to serialize.

    Returns:
        A JSON string ready to send as a WebSocket text frame.
    """
    raw = asdict(msg)
    raw["op"] = msg.op.value
    return json.dumps({k: v for k, v in raw.items() if v is not None})


def parse_frame(raw: str) -> NMBMessage:
    """Parse a JSON WebSocket text frame into an ``NMBMessage``.

    Args:
        raw: The raw JSON string received from the WebSocket.

    Returns:
        A populated ``NMBMessage`` instance.

    Raises:
        FrameValidationError: If the JSON is malformed or the ``op``
            field is missing or unrecognised.
    """
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise FrameValidationError(
            ErrorCode.INVALID_FRAME,
            f"Malformed JSON: {exc}",
        ) from exc

    if "op" not in data:
        raise FrameValidationError(
            ErrorCode.INVALID_FRAME,
            "Missing required field 'op'",
        )

    try:
        op = Op(data.pop("op"))
    except ValueError:
        raise FrameValidationError(
            ErrorCode.INVALID_FRAME,
            f"Unknown op: {data.get('op')}",
        )

    # Map JSON keys to dataclass field names
    field_map: dict[str, str] = {"from": "from_sandbox"}
    mapped: dict[str, Any] = {}
    for key, value in data.items():
        mapped[field_map.get(key, key)] = value

    return NMBMessage(op=op, **mapped)
