#!/usr/bin/env python3
"""Generate the resolved sandbox policy from the base template + .env secrets.

Reads policies/orchestrator.yaml (committed, no secrets) and injects
allowed_ips into endpoints that need SSRF bypass.  Both configuration
values are read from .env:

- ENDPOINTS_NEEDING_ALLOWED_IPS — comma-separated hostnames to inject.
- ALLOWED_IPS — comma-separated CIDRs to allow.

No defaults are hardcoded; both must be defined in .env.

Usage:
  make gen-policy                 # via Makefile
  PYTHONPATH=src python scripts/gen_policy.py   # standalone

Writes policies/orchestrator.resolved.yaml (gitignored).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Committed base template (no secrets).
BASE_POLICY = Path("policies/orchestrator.yaml")
# Output path for the fully-resolved policy (gitignored).
RESOLVED_POLICY = Path("policies/orchestrator.resolved.yaml")


def _load_dotenv(path: str = ".env") -> dict[str, str]:
    """Parse a dotenv file and return its key-value pairs.

    Args:
        path: Filesystem path to the dotenv file.  Returns an empty
            dict when the file does not exist.

    Returns:
        Mapping of variable names to their values as read from the file.
    """
    env_path = Path(path)
    values: dict[str, str] = {}
    if not env_path.is_file():
        return values
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("'\"")
        if key:
            values[key] = value
    return values


def main() -> None:
    """Generate the resolved sandbox policy file.

    Steps:
        1. Load environment variables from ``.env`` (if present).
        2. Read the base policy template.
        3. Inject ``allowed_ips`` CIDR ranges into every endpoint whose
           host appears in ``ENDPOINTS_NEEDING_ALLOWED_IPS``.
        4. Write the resolved policy to :data:`RESOLVED_POLICY`.

    Raises:
        SystemExit: If the base policy template is missing.
    """
    env = _load_dotenv()

    endpoints_raw = env.get("ENDPOINTS_NEEDING_ALLOWED_IPS", "")
    endpoints_needing_ips: set[str] = {
        h.strip() for h in endpoints_raw.split(",") if h.strip()
    }

    allowed_ips_raw = env.get("ALLOWED_IPS", "")
    allowed_ips: list[str] = [
        cidr.strip() for cidr in allowed_ips_raw.split(",") if cidr.strip()
    ]

    if not BASE_POLICY.is_file():
        print(f"Error: {BASE_POLICY} not found", file=sys.stderr)
        sys.exit(1)

    policy: dict[str, object] = yaml.safe_load(BASE_POLICY.read_text())

    injected: list[str] = []
    for _policy_name, policy_entry in policy.get("network_policies", {}).items():
        for endpoint in policy_entry.get("endpoints", []):
            host: str = endpoint.get("host", "")
            if host not in endpoints_needing_ips:
                continue
            if allowed_ips:
                endpoint["allowed_ips"] = allowed_ips
                injected.append(host)
            else:
                print(
                    f"  Warning: {host} needs allowed_ips but "
                    "ALLOWED_IPS is not set in .env",
                )

    with open(RESOLVED_POLICY, "w") as f:
        f.write("# AUTO-GENERATED by scripts/gen_policy.py — do not edit.\n")
        f.write(f"# Source: {BASE_POLICY}\n")
        f.write("# Regenerate: make gen-policy\n\n")
        yaml.dump(policy, f, default_flow_style=False, sort_keys=False)

    if injected:
        print(f"Policy generated: {RESOLVED_POLICY}")
        print(f"  allowed_ips injected for: {', '.join(injected)}")
        print(f"  CIDRs: {', '.join(allowed_ips)}")
    else:
        print(
            f"Policy generated: {RESOLVED_POLICY} "
            "(no allowed_ips — ALLOWED_IPS not set)",
        )


if __name__ == "__main__":
    main()
